# Generated by Django 5.2.8 on 2025-11-30 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='员工编号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.BooleanField(choices=[(True, '男'), (False, '女')], verbose_name='性别')),
                ('nation', models.CharField(blank=True, max_length=20, verbose_name='民族')),
                ('household_register', models.CharField(blank=True, max_length=100, null=True, verbose_name='户籍所在地')),
                ('id_card_number', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('native_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='籍贯')),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='出生地')),
                ('political_status', models.CharField(choices=[('party_member', '中共党员'), ('democratic_party', '民主党派'), ('masses', '群众'), ('other', '其他')], default='masses', max_length=20, verbose_name='政治面貌')),
                ('party_join_date', models.DateField(blank=True, null=True, verbose_name='入党时间')),
                ('democratic_party', models.BooleanField(default=False, verbose_name='是否民主党派')),
                ('democratic_party_join_date', models.DateField(blank=True, null=True, verbose_name='加入民主党派时间')),
                ('current_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='现任管理职务')),
                ('position_appointment_date', models.DateField(blank=True, null=True, verbose_name='任现职务时间')),
                ('position_level', models.CharField(blank=True, choices=[('level_1', '副局级'), ('level_2', '正处级'), ('level_3', '副处级'), ('level_4', '正科级'), ('level_5', '副科级'), ('level_6', '科员'), ('other', '其他')], max_length=20, null=True, verbose_name='现任职务级别')),
                ('professional_title', models.CharField(blank=True, choices=[('senior_researcher', '研究员（正高级）'), ('associate_researcher', '副研究员（副高级）'), ('research_assistant', '助理研究员（中级）'), ('research_intern', '研究实习员（初级）'), ('other', '其他')], max_length=20, null=True, verbose_name='职称')),
                ('title_appointment_date', models.DateField(blank=True, null=True, verbose_name='职称定职时间')),
                ('technical_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='现聘专技岗位')),
                ('technical_position_start_date', models.DateField(blank=True, null=True, verbose_name='专技岗起聘时间')),
                ('special_appointment', models.CharField(blank=True, max_length=100, null=True, verbose_name='特聘岗位')),
                ('special_appointment_start_date', models.DateField(blank=True, null=True, verbose_name='特聘岗位起聘时间')),
                ('full_time_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='全日制毕业院校')),
                ('full_time_major', models.CharField(blank=True, max_length=100, null=True, verbose_name='全日制所学专业')),
                ('full_time_education', models.CharField(blank=True, choices=[('doctor', '博士研究生'), ('master', '硕士研究生'), ('bachelor', '本科'), ('junior_college', '专科'), ('high_school', '高中'), ('other', '其他')], max_length=20, null=True, verbose_name='全日制最高学历')),
                ('full_time_degree', models.CharField(blank=True, choices=[('doctorate', '博士'), ('master', '硕士'), ('bachelor', '学士'), ('other', '其他'), ('none', '无')], default='none', max_length=20, null=True, verbose_name='全日制最后学位')),
                ('full_time_graduation_date', models.DateField(blank=True, null=True, verbose_name='全日制毕业（获学位）时间')),
                ('in_service_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='在职学习毕业院校')),
                ('in_service_major', models.CharField(blank=True, max_length=100, null=True, verbose_name='在职学习所学专业')),
                ('in_service_education', models.CharField(blank=True, choices=[('doctor', '博士研究生'), ('master', '硕士研究生'), ('bachelor', '本科'), ('junior_college', '专科'), ('high_school', '高中'), ('other', '其他')], max_length=20, null=True, verbose_name='在职学习所获学历')),
                ('in_service_degree', models.CharField(blank=True, choices=[('doctorate', '博士'), ('master', '硕士'), ('bachelor', '学士'), ('other', '其他'), ('none', '无')], default='none', max_length=20, null=True, verbose_name='在职学习所获学位')),
                ('highest_education', models.CharField(blank=True, choices=[('doctor', '博士研究生'), ('master', '硕士研究生'), ('bachelor', '本科'), ('junior_college', '专科'), ('high_school', '高中'), ('other', '其他')], max_length=20, null=True, verbose_name='最高学历')),
                ('highest_degree', models.CharField(blank=True, choices=[('doctorate', '博士'), ('master', '硕士'), ('bachelor', '学士'), ('other', '其他'), ('none', '无')], default='none', max_length=20, null=True, verbose_name='最高学位')),
                ('in_service_graduation_date', models.DateField(blank=True, null=True, verbose_name='在职学习毕业（获学位）时间')),
                ('work_start_date', models.DateField(blank=True, null=True, verbose_name='参加工作时间')),
                ('join_institute_date', models.DateField(blank=True, null=True, verbose_name='入所编制时间')),
                ('institute_household', models.BooleanField(default=False, verbose_name='是否所集户户口')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='办公电话')),
                ('mobile_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='电子邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='所在部门')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
